# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, unique=True)),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('description', models.CharField(max_length=5000)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.SmallIntegerField(default=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.Event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('return_ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideshare.Ride')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'demande de participation au trajet en attente de confirmation'), ('CONFIRMED', 'demande de participation au trajet validée'), ('CANCELLED', 'demande de participation au trajet annulée'), ('TIMED_OUT', 'demande de participation au trajet expirée')], default='PENDING', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.Location')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='rider',
            name='joining_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joining_rider', to='rideshare.Stop'),
        ),
        migrations.AddField(
            model_name='rider',
            name='leaving_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaving_rider', to='rideshare.Stop'),
        ),
        migrations.AddField(
            model_name='rider',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.Ride'),
        ),
        migrations.AddField(
            model_name='rider',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.Location'),
        ),
    ]
