# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
