# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stop',
            options={'ordering': ('time',)},
        ),
        migrations.AddField(
            model_name='ride',
            name='car_wear_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ride',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='ride',
            name='tolls_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
