# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_auto_20160807_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='other_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car_wear_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='fuel_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ride',
            name='tolls_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
