# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0002_ride_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Message pour les participants'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='phone',
            field=models.CharField(default='00 00 00 00 00', max_length=32, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Prix par participant'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='seats',
            field=models.SmallIntegerField(default=5, verbose_name='Nombre total de places'),
        ),
    ]
