# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_auto_20160807_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='car_wear_cost',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='fuel_cost',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='other_costs',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='tolls_cost',
        ),
        migrations.AddField(
            model_name='ride',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
