# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0003_auto_20160914_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
