# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0005_auto_20160813_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='precision',
            field=models.CharField(default='APPROXIMATE', max_length=48),
            preserve_default=False,
        ),
    ]
