# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0006_location_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(default='Île-de-France', max_length=255),
        ),
    ]
