# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0007_location_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='locality',
            field=models.CharField(default='Paris', max_length=255),
        ),
    ]
