# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0008_location_locality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='return_ride',
        ),
        migrations.AddField(
            model_name='ride',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
