# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rideshare', '0009_auto_20160824_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='riders',
            field=models.ManyToManyField(related_name='ride', through='rideshare.Rider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ride', to=settings.AUTH_USER_MODEL),
        ),
    ]
