# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0010_auto_20160825_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='joining_stop',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='leaving_stop',
        ),
    ]
