# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0011_auto_20160831_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='email',
            field=models.EmailField(default='no@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='rider',
            name='phone',
            field=models.CharField(default='00 00 00 00 00', max_length=32),
        ),
    ]
