# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0012_auto_20160906_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='status',
        ),
        migrations.AddField(
            model_name='rider',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rider',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='name',
            field=models.CharField(default='No Name', max_length=64),
        ),
    ]
