# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('rideshare', '0013_auto_20160908_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
    ]
