# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0014_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='user',
        ),
        migrations.AddField(
            model_name='ride',
            name='phone',
            field=models.CharField(default='00 00 00 00 00', max_length=32),
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
    ]
